version: "3.7"
services:
  api:
    build:
      context: ./api-service
    volumes:
      - ./api-service:/app
    expose:
      - "4567"
    ports:
      - "4567:4567"
    environment:
      - PORT=4567
      - RACK_ENV=development

  admin:
    build:
      context: ./admin-service
    command: npm run dev-server
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - SHORTENER_API_BASE_URL=http://127.0.0.1:4000/api/
      - SHORT_LINK_BASE_URI=http://127.0.0.1:4000/
    volumes:
      - ./admin-service:/app

  nginx:
    build:
      context: ./nginx
    environment:
      - SERVER_NAME=127.0.0.1:4000
      - API_HOST=api:4567
      - ADMIN_HOST=admin:8080
    command: run-dev
    ports:
      - "4000:80"
