version: "3.7"
services:
  api:
    build:
      context: ./api-service
    expose:
      - "4567"
    environment:
      - RACK_ENV=production

  admin:
    build:
      context: ./admin-service
    environment:
      - SHORTENER_API_BASE_URL=http://localhost:4000/api/
      - SHORT_LINK_BASE_URI=http://localhost:4000/
    volumes:
      - admin-service-static:/app/dist

  nginx:
    build:
      context: ./nginx
      args:
        server_name: "127.0.0.1:4000"
        api_host: "api:4567"
    ports:
      - "4000:80"
    volumes:
      - type: volume
        source: admin-service-static
        target: /usr/share/nginx/html/admin-service
        volume:
          nocopy: true

volumes:
  admin-service-static:
